{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Banned IP locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(fail2ban_banned_ip{latitude!='0',longitude!='0'}) by (latitude, longitude, city)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Banned ip for jails",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fail2ban_banned_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current failed count",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 4 },
   "targets": [
    { "expr": "fail2ban_failed_current", "legendFormat": "{{jail}}" }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "fail2ban_banned_ip", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}